import "@/styles/globals.css";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import Head from "next/head";
import { useRouter } from "next/router";

import { api } from "@/utils/api";
import { ThemeProvider } from "@/components/theme-provider";
import { Layout } from "@/components/dashboard/layout";
import Link from "next/link";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>RouteMaster</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={session}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {router.route !== "/" ? (
            <Layout>
              <Component {...pageProps} />
            </Layout>
          ) : (
            <Component {...pageProps} />
          )}
          <Link
            className="flex items-center justify-center border p-4 text-lg"
            href={"https://github.com/Nahrin-Malakes"}
            target="_blank"
          >
            Made with ❤️ by Nahrin Malakes
          </Link>
        </ThemeProvider>
      </SessionProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
